import { getTheme } from "@/actions/theme";
import "@/app/globals.css";
import RootProviders from "@/providers/root";
import { cn } from "@/utils/styles";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { FC, PropsWithChildren } from "react";

const font = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  fallback: ["Arial", "Helvetica", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = async (props) => {
  const { children } = props;
  const defaultTheme = await getTheme();
  return (
    <html lang="en" data-theme={defaultTheme}>
      <body className={cn(font.variable, "antialiased")}>
        <RootProviders defaultTheme={defaultTheme}>{children}</RootProviders>
      </body>
    </html>
  );
};

export default RootLayout;
