import { cn } from "@/utils/styles";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { FC, PropsWithChildren } from "react";
import "./globals.css";

const font = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = (props) => {
  const { children } = props;
  return (
    <html lang="en">
      <body className={cn(font.variable, "antialiased")}>{children}</body>
    </html>
  );
};

export default RootLayout;
